# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-21 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codenerix_storages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storagebatch',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'list'), 'verbose_name': "Storage's Batch", 'verbose_name_plural': "Storage's Batchs"},
        ),
    ]
