# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-18 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenerix_storages', '0003_auto_20180118_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageboxstructure',
            name='max_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Max weight'),
        ),
    ]
