# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-19 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codenerix_invoicing', '0013_salesorderdocument_removed'),
        ('codenerix_storages', '0013_auto_20180216_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryinline',
            name='purchasesorder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_lines', to='codenerix_invoicing.PurchasesOrder', verbose_name='Inventory line'),
            preserve_default=False,
        ),
    ]
