# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-14 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenerix_storages', '0021_auto_20180413_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='processed',
            field=models.BooleanField(default=False, editable=False, verbose_name='Processed'),
        ),
        migrations.AddField(
            model_name='inventoryin',
            name='processed',
            field=models.BooleanField(default=False, editable=False, verbose_name='Processed'),
        ),
        migrations.AddField(
            model_name='inventoryout',
            name='processed',
            field=models.BooleanField(default=False, editable=False, verbose_name='Processed'),
        ),
    ]
