# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-30 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codenerix_storages', '0027_auto_20180430_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomingalbaran',
            name='date',
        ),
        migrations.RemoveField(
            model_name='outgoingalbaran',
            name='date',
        ),
        migrations.RemoveField(
            model_name='requeststock',
            name='date',
        ),
    ]
