# Generated by Django 4.0.4 on 2022-05-13 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codenerix_products', '0013_alter_attribute_public_alter_brand_outstanding_and_more'),
        ('codenerix_geodata', '0003_auto_20180118_1209'),
        ('codenerix_storages', '0030_auto_20180708_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryinline',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_%(class)s', to='codenerix_storages.storagebox', verbose_name='Box'),
        ),
        migrations.AlterField(
            model_name='inventoryinline',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_%(class)s', to='codenerix_storages.storageoperator', verbose_name='Storage Operator'),
        ),
        migrations.AlterField(
            model_name='inventoryinline',
            name='product_final',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_%(class)s', to='codenerix_products.productfinal', verbose_name='Product Final'),
        ),
        migrations.AlterField(
            model_name='inventoryinline',
            name='product_unique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storage_%(class)s', to='codenerix_products.productunique', verbose_name='Product Unique'),
        ),
        migrations.AlterField(
            model_name='inventoryline',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_%(class)s', to='codenerix_storages.storagebox', verbose_name='Box'),
        ),
        migrations.AlterField(
            model_name='inventoryline',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_%(class)s', to='codenerix_storages.storageoperator', verbose_name='Storage Operator'),
        ),
        migrations.AlterField(
            model_name='inventoryline',
            name='product_final',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_%(class)s', to='codenerix_products.productfinal', verbose_name='Product Final'),
        ),
        migrations.AlterField(
            model_name='inventoryline',
            name='product_unique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storage_%(class)s', to='codenerix_products.productunique', verbose_name='Product Unique'),
        ),
        migrations.AlterField(
            model_name='inventoryoutline',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_%(class)s', to='codenerix_storages.storagebox', verbose_name='Box'),
        ),
        migrations.AlterField(
            model_name='inventoryoutline',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_%(class)s', to='codenerix_storages.storageoperator', verbose_name='Storage Operator'),
        ),
        migrations.AlterField(
            model_name='inventoryoutline',
            name='product_final',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_%(class)s', to='codenerix_products.productfinal', verbose_name='Product Final'),
        ),
        migrations.AlterField(
            model_name='inventoryoutline',
            name='product_unique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storage_%(class)s', to='codenerix_products.productunique', verbose_name='Product Unique'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_geo_addresses', to='codenerix_geodata.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_geo_addresses', to='codenerix_geodata.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_geo_addresses', to='codenerix_geodata.province', verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_geo_addresses', to='codenerix_geodata.region', verbose_name='Region'),
        ),
    ]
